[package]
name = "pyvirtualcam-py"
version = "0.0.0"
edition = "2021"
license = "GPL-2.0-only"

[lib]
name = "_native_linux_v4l2loopback"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.21"
pyvirtualcam-core = { path = "../pyvirtualcam-core" }
pyo3 = { version = "0.21", features = ["extension-module"] }
